### PR TITLE
Update blacklist2.js

### PR DESCRIPTION
**Pull request by iszlai**
Added banks from Hungary to blacklist

### CODE REVIEW

**Comment by lengstrom** [comment]
Could you either fix the conflicts or comment the banks you added? Thanks!

**Comment by anishathalye** [comment]
Also, if we put one string per line and have it sorted, it'll make this kind of thing a lot easier (we'll see nice diffs).

**Comment by lengstrom** [comment]
Yeah, that's a good idea. I'll do that tonight!

**Comment by lengstrom** [comment]
Just did it now, is it possible you could submit again?

**Comment by iszlai** [comment]
Sure as soon as I get in front of a pc

**Pull request closed without merging**
