### PR TITLE
Quick Blacklist feature

### PR DESCRIPTION
**Pull request by morris-jason**
### Enables a Quick Blacklist feature in the popup menu.
When clicked, the current tab url is added to the in-cache blacklist. 
Any time the popup is opened, popup.js checks to make to see if the url is blacklisted. If it is, the Quick Blacklist button turns green, indicating the site is blacklisted.

Sorry for the auto indentation fixes! Atom -__-

### CODE REVIEW

**Comment by morris-jason** [comment]
@lengstrom Have you read over the changes yet? What do you think?

**Comment by lengstrom** [comment]
@morris-jason  I haven't had time to review the changes yet, this last weekend I was busy organizing an event on my campus so this week I need to catch up with my schoolwork. I will review your changes by next Monday, sorry about the wait!

**Comment by morris-jason** [comment]
No problem. Good luck with school. 
-Jason

**Comment by morris-jason** [comment]
Awsome!! Thanks!

**Pull request merged**
